# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
