# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
    ]
