# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0002_category_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='views',
            new_name='visits',
        ),
    ]
