# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0005_category_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
    ]
