# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
