# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0006_category_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='picture',
            new_name='image',
        ),
    ]
