# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
