# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0009_auto_20180315_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
