# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0010_auto_20180315_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
