# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemy', '0013_auto_20180317_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=26),
        ),
    ]
